In [38]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2, 3], [3, 4, 5], [5, 6, 7]], columns=['A', 'B','C'], index=["x", "y", "z"])

In [10]:
df.head()

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [12]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   3.0  4.0  5.0
std    2.0  2.0  2.0
min    1.0  2.0  3.0
25%    2.0  3.0  4.0
50%    3.0  4.0  5.0
75%    4.0  5.0  6.0
max    5.0  6.0  7.0

In [13]:
df.shape

(3, 3)

In [14]:
df["A"].unique()

array([1, 3, 5])

In [15]:
df.size

9

### Loading DataFrames from files

In [91]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [64]:
results = pd.read_parquet('./data/results.parquet')
bios = pd.read_csv('./data/bios.csv')

### Accessing Data with Pandas

In [18]:
coffee.sample(10)

          Day Coffee Type  Units Sold
6    Thursday    Espresso          40
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
13     Sunday       Latte          35
4   Wednesday    Espresso          35
8      Friday    Espresso          45
10   Saturday    Espresso          45
7    Thursday       Latte          30
2     Tuesday    Espresso          30

In [19]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [20]:
coffee.loc[5:12]

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45

In [21]:
coffee.loc[1:5, ["Day", "Units Sold"]]

         Day  Units Sold
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25

In [22]:
coffee.iloc[1:5, [0, 2]]

         Day  Units Sold
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [23]:
# coffee.loc[1:3, "Units Sold"] = 10

In [24]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [25]:
# for index, row in coffee.iterrows():
#     print(row["Day"], row["Units Sold"])

### Filtering Data

In [26]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [27]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [28]:
# bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [29]:
bios[bios['name'].str.contains("neal", case=False, na=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
11357,11417,Cindy Neale-Ishoy,1952-06-19,Edmonton,Alberta,CAN,Canada,159.0,59.0,NaN
12224,12290,Neale Lavis,1930-06-11,Murwillumbah,New South Wales,AUS,Australia,171.0,73.0,2019-10-07
12670,12739,Neal Shapiro,1945-07-22,NaN,NaN,NaN,United States,175.0,70.0,NaN
22005,22164,Neal Mallett,1957-09-30,Berlin,Berlin,GER,Great Britain,188.0,75.0,NaN
25072,25262,Jack Neale,1917-02-11,London,England,GBR,Great Britain,NaN,NaN,1977-12-16
28272,28484,Margaret Thomas-Neale,1931-08-22,Cardiff,Wales,GBR,Great Britain,152.0,52.0,NaN
29918,30144,Ian Neale,1954-08-11,NaN,NaN,NaN,Great Britain,180.0,70.0,NaN
42060,42383,George Neal,1894-01-14,Smallburgh,England,GBR,Great Britain,NaN,NaN,1955-10-20
44289,44629,Neal Caloia,1970-04-09,Cottage Grove,Oregon,USA,United States,185.0,82.0,NaN
44760,45102,Gail Neall,1955-08-02,Sydney,New South Wales,AUS,Australia,163.0,52.0,NaN
58122,58536,Neal Kranz,1966-08-07,NaN,NaN,NaN,Guam,190.0,127.0,NaN
62445,62908,O'Neal Marshall,1971-08-25,NaN,NaN,NaN,Barbados,178.0,87.0,NaN
62491,62955,Neal McDonald,1963-07-22,Brighton,England,GBR,Great Britain,183.0,87.0,NaN
77338,77929,Lacey O'Neal,1944-03-30,Chicago,Illinois,USA,United States,170.0,62.0,NaN
78244,78835,McClinton Neal,1968-07-11,Dallas,Texas,USA,United States,193.0,88.0,NaN
83732,84396,Neal Broten,1959-11-29,Roseau,Minnesota,USA,United States,175.0,70.0,NaN
91430,92159,Neal Marshall,1969-06-13,Victoria,British Columbia,CAN,Canada,182.0,77.0,NaN
91870,92601,Neal Byrne,1976-06-15,Dublin,Dublin,IRL,Ireland,185.0,80.0,NaN
94999,95767,Bill Neale,1943-03-09,Fort Erie,Ontario,CAN,Canada,NaN,NaN,NaN
112185,113440,Blaine Neal,1978-04-06,Marlton,New Jersey,USA,United States,196.0,114.0,NaN
112681,113964,Teneal Attard,1985-03-16,Mackay,Queensland,AUS,Australia,161.0,59.0,NaN
120006,121854,Mark Kenneally,1981-04-18,Dublin,Dublin,IRL,Ireland,192.0,76.0,NaN
123856,126099,Teneale Hatton,1990-01-13,Queenstown,Otago,NZL,New Zealand,167.0,64.0,NaN
124392,126692,Lia Neal,1995-02-13,NaN,NaN,NaN,United States,178.0,75.0,NaN
126687,129065,Leah Neale,1995-08-01,Ipswich,Queensland,AUS,Australia,173.0,66.0,NaN
128726,131290,Brooke Neal,1992-07-04,Whangarei,Northland,NZL,New Zealand,182.0,71.0,NaN
131286,134062,Tim Kneale,1982-10-16,Douglas,Isle of Man,IOM,Great Britain,187.0,85.0,NaN
132506,135381,Shay Neal,1990-06-04,Whangarei,Northland,NZL,New Zealand,176.0,75.0,NaN
139726,143204,Neal Skupski,1989-12-01,Liverpool,England,GBR,Great Britain,NaN,NaN,NaN

In [34]:
bios[bios['born_country'].isin(['USA', 'FRA'])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [35]:
bios.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

### Adding / Removing Columns

In [36]:
coffee['price'] = 4.99

In [37]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [40]:
coffee['new_price'] = np.where(coffee['Coffee Type']== 'Espresso', 3.99,5.99)

In [41]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [42]:
coffee.drop(columns="price", inplace=True)
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [43]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [46]:
coffee.rename(columns={'new_price':'price'}, inplace=True)

In [47]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

### Let's try with bios

In [48]:
bios_new = bios.copy()

In [49]:
bios_new['first_name'] = bios_new['name'].str.split(" ").str[0]

In [50]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [51]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(1), str(7)
memory usage: 19.6+ MB

In [52]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [54]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 20.7+ MB

In [55]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

bios_new[['name', 'born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [56]:
bios_new.to_csv('./data/bios_new.csv', index=False)

In [57]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))

In [59]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [62]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 and row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'Heavyweight'

bios_new['Category'] = bios_new.apply(categorize_athlete, axis=1)

In [65]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight

### Merging & Concatenating Data

In [68]:
nocs = pd.read_csv('./data/noc_regions.csv')

In [70]:
new_merge = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [74]:
new_merge.rename(columns={'region': 'born_country_full'}, inplace=True)

In [76]:
new_merge[new_merge['NOC_x'] != new_merge['born_country_full']][['name', 'NOC_x', 'born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

### Handling Null Values

In [83]:
coffee.loc[[0,1], "Units Sold"] = np.nan

In [86]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
dtype: int64

In [87]:
coffee= coffee.fillna(coffee['Units Sold'].mean())

In [92]:
coffee.loc[[2,3], "Units Sold"] = np.nan

In [93]:
coffee['Units Sold'].interpolate()

0     25.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [94]:
coffee[coffee["Units Sold"].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [95]:
coffee[coffee["Units Sold"].isna()]

       Day Coffee Type  Units Sold
2  Tuesday    Espresso         NaN
3  Tuesday       Latte         NaN

### Aggregating Data

In [96]:
bios['born_city'].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [97]:
bios[bios['born_country']== 'USA']['born_region'].value_counts().head()

born_region
California       1634
New York          990
Illinois          585
Pennsylvania      530
Massachusetts     530
Name: count, dtype: int64